name: Convert Documents

on:
  push:
    branches:
      - main
      - stable

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    name: <(^v^)> Documentation Conversion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code ï¸ğŸ“
        uses: actions/checkout@v3

      - name: Install and Build ğŸ”§
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          npm i -g c4builder
          c4builder
          cp src/_sidebar.md docs/_sidebar.md
          cp src/_coverpage.md docs/_coverpage.md
      - name: push ğŸ“š
        if: github.ref == 'refs/heads/main'
        uses: actions-x/commit@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
        with:
          name: GitHub Actions Automatic Commit
          files: ./docs
          message: "[GITOPS] Pipeline updated documentation"

      - name: push to deploy branch ğŸ“¬
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: ./docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

